alert("let table = document.getElementById('age-table')")
alert("document.querySelectorAll('#age-table label')")
alert("table.rows[0].cells[0]")
alert(`document.querySelector('form[name="search"]')`)
alert("form.querySelector('input')")
alert("let input = form.querySelectorAll('input') \n inputs[inputs.length-1]")